# -*- coding: utf-8 -*-
"""Insurance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brXcsrW8oY6D_pwbiIjrOdFqa24AsYAR

# **Insurance Prediction Using Linear Regression**
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv("/content/insurance_data(with_outlier).csv")

data.info()

data.head()

X = data[['age', 'bought_insurance']]
y = data['bought_insurance']

model = LinearRegression()
model.fit(X, y)

new_data = pd.DataFrame({'age': [30], 'bought_insurance': [0]})
predictions = model.predict(new_data)
print(predictions)

from sklearn.metrics import r2_score

r2 = r2_score(y, model.predict(X))
print("R-squared:", r2)