# -*- coding: utf-8 -*-
"""Iris Flower Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WcKGpDe6PtTnMgkVI-5057RHrtIytCY0

#  IRIS FLOWER CLASSIFICATION Using Decision Tree

# **Importing libraries**
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report

"""**Data**"""

iris = load_iris()
print(iris)

X=iris.data
y=iris.target

"""**Test Train Validation**"""

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=30)
classification_model=DecisionTreeClassifier(random_state=30)
classification_model.fit(X_train,y_train)
y_predicted=classification_model.predict(X_test)

"""**Accuracy Of The Model & Classification Report**"""

accuracy=accuracy_score(y_test,y_predicted)
print("Accuracy obtained for the model is",accuracy)
print("Classification Report",classification_report(y_test,y_predicted))